"""create users and warehouses tables

Revision ID: 51dc5e75a64f
Revises: c99a61622a9f
Create Date: 2026-07-27 18:53:07.156647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dc5e75a64f'
down_revision: Union[str, Sequence[str], None] = 'c99a61622a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.create_foreign_key(None, 'warehouses', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'created_at')
    op.drop_column('warehouses', 'owner_id')
    # ### end Alembic commands ###
