"""add warehouse pilot profiles and requirement assessments

Revision ID: b657ffadfdac
Revises: o0a1b2c3d4e5
Create Date: 2026-09-13 10:34:31.643608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b657ffadfdac'
down_revision: Union[str, Sequence[str], None] = 'o0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_commercial_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('listing_status', sa.Enum('ACTIVE', 'INACTIVE', 'RESERVED', 'OCCUPIED', 'UNDER_NEGOTIATION', name='listingstatus'), nullable=True),
    sa.Column('available_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('minimum_leasable_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maximum_leasable_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('lease_term_min_months', sa.Integer(), nullable=True),
    sa.Column('lease_term_max_months', sa.Integer(), nullable=True),
    sa.Column('expected_rent_per_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_monthly_rent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('security_deposit_months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('escalation_percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('escalation_frequency_months', sa.Integer(), nullable=True),
    sa.Column('maintenance_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maintenance_charge_type', sa.Enum('PER_SQFT', 'MONTHLY', 'INCLUDED', name='maintenancechargetype'), nullable=True),
    sa.Column('property_tax_included', sa.Boolean(), nullable=True),
    sa.Column('electricity_terms', sa.Text(), nullable=True),
    sa.Column('water_terms', sa.Text(), nullable=True),
    sa.Column('rent_negotiable', sa.Boolean(), nullable=True),
    sa.Column('lease_term_negotiable', sa.Boolean(), nullable=True),
    sa.Column('fitout_support_available', sa.Boolean(), nullable=True),
    sa.Column('client_specific_modifications_possible', sa.Boolean(), nullable=True),
    sa.Column('modification_notes', sa.Text(), nullable=True),
    sa.Column('commercial_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'warehouse_id', name='uq_warehouse_commercial_profile_org_warehouse')
    )
    op.create_index('ix_warehouse_commercial_profiles__warehouse_id', 'warehouse_commercial_profiles', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_commercial_profiles_organization_id'), 'warehouse_commercial_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warehouse_commercial_profiles_warehouse_id'), 'warehouse_commercial_profiles', ['warehouse_id'], unique=False)
    op.create_table('warehouse_operational_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_category', sa.String(length=100), nullable=True),
    sa.Column('construction_type', sa.String(length=50), nullable=True),
    sa.Column('building_structure', sa.String(length=100), nullable=True),
    sa.Column('building_condition', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('number_of_blocks', sa.Integer(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('usable_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_plot_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('office_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('parking_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approach_road_width_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('approach_road_surface', sa.String(length=50), nullable=True),
    sa.Column('truck_access', sa.String(length=50), nullable=True),
    sa.Column('turning_radius_adequate', sa.Boolean(), nullable=True),
    sa.Column('vehicle_parking_available', sa.Boolean(), nullable=True),
    sa.Column('truck_parking_capacity', sa.Integer(), nullable=True),
    sa.Column('loading_vehicle_access', sa.Boolean(), nullable=True),
    sa.Column('container_access', sa.Boolean(), nullable=True),
    sa.Column('loading_bays_count', sa.Integer(), nullable=True),
    sa.Column('dock_levelers_count', sa.Integer(), nullable=True),
    sa.Column('dock_height_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ground_level_loading_available', sa.Boolean(), nullable=True),
    sa.Column('covered_loading_area', sa.Boolean(), nullable=True),
    sa.Column('loading_platform_available', sa.Boolean(), nullable=True),
    sa.Column('loading_equipment_available', sa.Boolean(), nullable=True),
    sa.Column('forklift_available', sa.Boolean(), nullable=True),
    sa.Column('forklift_capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pallet_handling_available', sa.Boolean(), nullable=True),
    sa.Column('material_handling_notes', sa.Text(), nullable=True),
    sa.Column('power_connection_available', sa.Boolean(), nullable=True),
    sa.Column('sanctioned_power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('backup_power_available', sa.Boolean(), nullable=True),
    sa.Column('generator_capacity_kva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transformer_available', sa.Boolean(), nullable=True),
    sa.Column('water_supply_available', sa.Boolean(), nullable=True),
    sa.Column('drainage_available', sa.Boolean(), nullable=True),
    sa.Column('internet_available', sa.Boolean(), nullable=True),
    sa.Column('telecom_available', sa.Boolean(), nullable=True),
    sa.Column('fire_safety_system', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fire_extinguishers_available', sa.Boolean(), nullable=True),
    sa.Column('hydrant_system_available', sa.Boolean(), nullable=True),
    sa.Column('sprinkler_system_available', sa.Boolean(), nullable=True),
    sa.Column('fire_noc_available', sa.Boolean(), nullable=True),
    sa.Column('emergency_exits_available', sa.Boolean(), nullable=True),
    sa.Column('emergency_lighting_available', sa.Boolean(), nullable=True),
    sa.Column('security_available', sa.Boolean(), nullable=True),
    sa.Column('cctv_available', sa.Boolean(), nullable=True),
    sa.Column('boundary_security', sa.Boolean(), nullable=True),
    sa.Column('security_notes', sa.Text(), nullable=True),
    sa.Column('flooring_type', sa.String(length=50), nullable=True),
    sa.Column('floor_condition', sa.String(length=50), nullable=True),
    sa.Column('floor_levelness', sa.String(length=50), nullable=True),
    sa.Column('floor_load_capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pallet_storage_supported', sa.Boolean(), nullable=True),
    sa.Column('racking_supported', sa.Boolean(), nullable=True),
    sa.Column('maximum_rack_height_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('storage_type_supported', sa.String(length=50), nullable=True),
    sa.Column('operational_status', sa.Enum('READY', 'PARTIALLY_READY', 'UNDER_PREPARATION', 'UNDER_CONSTRUCTION', 'INACTIVE', name='operationalstatus'), nullable=True),
    sa.Column('available_for_site_visit', sa.Boolean(), nullable=True),
    sa.Column('site_visit_notice_hours', sa.Integer(), nullable=True),
    sa.Column('operational_notes', sa.Text(), nullable=True),
    sa.Column('improvement_plan', sa.Text(), nullable=True),
    sa.Column('improvement_budget_estimate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'warehouse_id', name='uq_warehouse_operational_profile_org_warehouse')
    )
    op.create_index('ix_warehouse_operational_profiles__warehouse_id', 'warehouse_operational_profiles', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_operational_profiles_organization_id'), 'warehouse_operational_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warehouse_operational_profiles_warehouse_id'), 'warehouse_operational_profiles', ['warehouse_id'], unique=False)
    op.create_table('warehouse_requirement_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('requirement_source', sa.String(length=50), nullable=True),
    sa.Column('captured_by_user_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_confidence', sa.Enum('CONFIRMED', 'LIKELY', 'PARTIAL', 'UNVERIFIED', name='requirementconfidence'), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preferred_rent_per_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferred_lease_months', sa.Integer(), nullable=True),
    sa.Column('deposit_preference', sa.String(length=100), nullable=True),
    sa.Column('move_in_target_date', sa.Date(), nullable=True),
    sa.Column('preferred_city', sa.String(length=100), nullable=True),
    sa.Column('preferred_state', sa.String(length=100), nullable=True),
    sa.Column('preferred_micro_markets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('maximum_distance_from_city_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('maximum_distance_from_highway_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('requirement_flexibility', sa.Enum('STRICT', 'MODERATE', 'FLEXIBLE', name='requirementflexibility'), nullable=True),
    sa.Column('negotiable_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('possible_tradeoffs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('client_priority_notes', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('DRAFT', 'CAPTURED', 'VALIDATED', 'OUTDATED', 'REJECTED', name='validationstatus'), nullable=False),
    sa.Column('validated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'company_id', name='uq_warehouse_requirement_assessment_org_company')
    )
    op.create_index(op.f('ix_warehouse_requirement_assessments_captured_by_user_id'), 'warehouse_requirement_assessments', ['captured_by_user_id'], unique=False)
    op.create_index(op.f('ix_warehouse_requirement_assessments_company_id'), 'warehouse_requirement_assessments', ['company_id'], unique=False)
    op.create_index(op.f('ix_warehouse_requirement_assessments_organization_id'), 'warehouse_requirement_assessments', ['organization_id'], unique=False)
    op.alter_column('company_contacts', 'contact_quality_explanation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('company_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_icp_assessments', 'factors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    op.alter_column('company_icp_assessments', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_company_icp_assessments'), 'company_icp_assessments', type_='unique')
    op.create_unique_constraint('uq_company_icp_assessment', 'company_icp_assessments', ['organization_id', 'company_id'])
    op.alter_column('company_intelligence_profiles', 'operational_geography',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.alter_column('company_intelligence_profiles', 'indicator_evidence',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.alter_column('company_intelligence_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_intelligence_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_next_best_actions', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_opportunity_assessments', 'explanation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    op.alter_column('company_opportunity_assessments', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_company_opportunity_assessments'), 'company_opportunity_assessments', type_='unique')
    op.create_unique_constraint('uq_company_opportunity_assessment', 'company_opportunity_assessments', ['organization_id', 'company_id'])
    op.alter_column('company_warehouse_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_requirement_profiles', 'requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    op.alter_column('company_warehouse_requirement_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_requirement_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_company_warehouse_requirement_profiles__company_id'), table_name='company_warehouse_requirement_profiles')
    op.drop_index(op.f('ix_company_warehouse_requirement_profiles__organization_id'), table_name='company_warehouse_requirement_profiles')
    op.create_index(op.f('ix_company_warehouse_requirement_profiles_company_id'), 'company_warehouse_requirement_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_warehouse_requirement_profiles_organization_id'), 'company_warehouse_requirement_profiles', ['organization_id'], unique=False)
    op.alter_column('warehouse_capability_profiles', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    op.alter_column('warehouse_capability_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('warehouse_capability_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_warehouse_capability_profiles__organization_id'), table_name='warehouse_capability_profiles')
    op.drop_index(op.f('ix_warehouse_capability_profiles__warehouse_id'), table_name='warehouse_capability_profiles')
    op.create_index(op.f('ix_warehouse_capability_profiles_organization_id'), 'warehouse_capability_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warehouse_capability_profiles_warehouse_id'), 'warehouse_capability_profiles', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouses_organization_id'), 'warehouses', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_organization_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouse_capability_profiles_warehouse_id'), table_name='warehouse_capability_profiles')
    op.drop_index(op.f('ix_warehouse_capability_profiles_organization_id'), table_name='warehouse_capability_profiles')
    op.create_index(op.f('ix_warehouse_capability_profiles__warehouse_id'), 'warehouse_capability_profiles', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_capability_profiles__organization_id'), 'warehouse_capability_profiles', ['organization_id'], unique=False)
    op.alter_column('warehouse_capability_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('warehouse_capability_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('warehouse_capability_profiles', 'capabilities',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_company_warehouse_requirement_profiles_organization_id'), table_name='company_warehouse_requirement_profiles')
    op.drop_index(op.f('ix_company_warehouse_requirement_profiles_company_id'), table_name='company_warehouse_requirement_profiles')
    op.create_index(op.f('ix_company_warehouse_requirement_profiles__organization_id'), 'company_warehouse_requirement_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_warehouse_requirement_profiles__company_id'), 'company_warehouse_requirement_profiles', ['company_id'], unique=False)
    op.alter_column('company_warehouse_requirement_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_requirement_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_requirement_profiles', 'requirements',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('company_warehouse_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_warehouse_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_company_opportunity_assessment', 'company_opportunity_assessments', type_='unique')
    op.create_unique_constraint(op.f('uq_company_opportunity_assessments'), 'company_opportunity_assessments', ['organization_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('company_opportunity_assessments', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_opportunity_assessments', 'explanation',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('company_next_best_actions', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_intelligence_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_intelligence_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_intelligence_profiles', 'indicator_evidence',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('company_intelligence_profiles', 'operational_geography',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_company_icp_assessment', 'company_icp_assessments', type_='unique')
    op.create_unique_constraint(op.f('uq_company_icp_assessments'), 'company_icp_assessments', ['organization_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('company_icp_assessments', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_icp_assessments', 'factors',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('company_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_contacts', 'contact_quality_explanation',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_warehouse_requirement_assessments_organization_id'), table_name='warehouse_requirement_assessments')
    op.drop_index(op.f('ix_warehouse_requirement_assessments_company_id'), table_name='warehouse_requirement_assessments')
    op.drop_index(op.f('ix_warehouse_requirement_assessments_captured_by_user_id'), table_name='warehouse_requirement_assessments')
    op.drop_table('warehouse_requirement_assessments')
    op.drop_index(op.f('ix_warehouse_operational_profiles_warehouse_id'), table_name='warehouse_operational_profiles')
    op.drop_index(op.f('ix_warehouse_operational_profiles_organization_id'), table_name='warehouse_operational_profiles')
    op.drop_index('ix_warehouse_operational_profiles__warehouse_id', table_name='warehouse_operational_profiles')
    op.drop_table('warehouse_operational_profiles')
    op.drop_index(op.f('ix_warehouse_commercial_profiles_warehouse_id'), table_name='warehouse_commercial_profiles')
    op.drop_index(op.f('ix_warehouse_commercial_profiles_organization_id'), table_name='warehouse_commercial_profiles')
    op.drop_index('ix_warehouse_commercial_profiles__warehouse_id', table_name='warehouse_commercial_profiles')
    op.drop_table('warehouse_commercial_profiles')
    # ### end Alembic commands ###
